#!/bin/bash

# Usage: ./genaudios_fromdb.sh entity_type
# Example: ./genaudios_fromdb.sh audio_dialogue_lines

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MYSQL_ARGS=$("$SCRIPT_DIR"/db_name.sh main-conn)

ENTITY_TYPE="$1"

if [ -z "$ENTITY_TYPE" ]; then
  echo "Usage: $0 entity_type"
  echo "Available types: audio_dialogue_lines, audio_ambiences, audio_cues, audio_foleys, audio_fxsounds, audio_themes"
  exit 1
fi

# -----------------------------
# Create a new map_run
# -----------------------------
MAP_RUN_ID=$(mysql $MYSQL_ARGS -N -e "
INSERT INTO map_runs (entity_type, note) 
VALUES ('$ENTITY_TYPE', 'Generated by genaudios_fromdb.sh (Async/Polling TTS)'); 
SELECT LAST_INSERT_ID();
")

echo "Created new map_run ID: $MAP_RUN_ID for $ENTITY_TYPE"

# -----------------------------
# Build Query based on Entity Type
# -----------------------------
declare -a IDS
declare -a TEXTS
declare -a MODELS

if [ "$ENTITY_TYPE" == "audio_dialogue_lines" ]; then
    # Join to get specific character voice. 
    # If no identity found, defaults to 'en_US_amy'
    SQL_QUERY="
    SELECT 
        t1.id, 
        t1.description, 
        COALESCE(t2.name, 'en_US_amy') 
    FROM audio_dialogue_lines t1 
    LEFT JOIN audio_voice_identity t2 ON t1.audio_voice_identity_id = t2.id 
    WHERE t1.regenerate_audios=1"
else
    # For SFX/Ambience
    SQL_QUERY="
    SELECT 
        id, 
        description, 
        'en_US_amy' 
    FROM $ENTITY_TYPE 
    WHERE regenerate_audios=1"
fi

# -----------------------------
# Fetch Data
# -----------------------------
while IFS=$'\t' read -r id text model; do
  IDS+=("$id")
  TEXTS+=("$text")
  MODELS+=("$model")
done < <(mysql $MYSQL_ARGS -N -e "$SQL_QUERY")

TOTAL=${#IDS[@]}
echo "Found $TOTAL entities flagged for audio generation."

# -----------------------------
# Process Loop
# -----------------------------
for i in "${!IDS[@]}"; do
  E_ID="${IDS[$i]}"
  E_TEXT="${TEXTS[$i]}"
  E_MODEL="${MODELS[$i]}"

  # ---------------------------------------------------------
  # SAFETY NET: Force Sentence Breaks
  # ---------------------------------------------------------
  # 1. Replace newlines with " . " (period + space).
  # 2. Replace multiple spaces with single space.
  E_TEXT_CLEAN=$(echo "$E_TEXT" | sed ':a;N;$!ba;s/[\r\n]\+/ . /g' | tr -s ' ')

  echo "[Processing $i/$TOTAL] ID:$E_ID Model:$E_MODEL"

  # Invoke the worker script (Async/Polling client)
  "$SCRIPT_DIR/genaudio_db.sh" "$E_TEXT_CLEAN" "$MAP_RUN_ID" "$ENTITY_TYPE" "$E_ID" "$E_MODEL"

  # Update active_map_run_id on the entity
  mysql $MYSQL_ARGS -e "
    UPDATE $ENTITY_TYPE 
    SET active_map_run_id = '$MAP_RUN_ID'
    WHERE id = '$E_ID';
  "

  # Cool down - keeping this is good practice for mobile devices running heavy polling loops
  echo "Cooling down (2s)..."
  sleep 2

done

echo "Done processing audios for '$ENTITY_TYPE'."
