#!/bin/bash

# Usage: ./gendias_fromdb.sh entity_type
# Example: ./gendias_fromdb.sh audio_dialogue_lines

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MYSQL_ARGS=$("$SCRIPT_DIR"/db_name.sh main-conn)

ENTITY_TYPE="$1"

if [ -z "$ENTITY_TYPE" ]; then
  echo "Usage: $0 entity_type"
  echo "Available types: audio_dialogue_lines, audio_ambiences, audio_cues, audio_foleys, audio_fxsounds, audio_themes"
  exit 1
fi

# -----------------------------
# Create a new map_run
# -----------------------------
# 2>/dev/null silences MySQL warnings
MAP_RUN_ID=$(mysql $MYSQL_ARGS -N -e "
INSERT INTO map_runs (entity_type, note) 
VALUES ('$ENTITY_TYPE', 'Generated by gendias_fromdb.sh (Pollinations AI TTS)'); 
SELECT LAST_INSERT_ID();
" 2>/dev/null)

echo "[Wrapper] Started. Map Run ID: $MAP_RUN_ID ($ENTITY_TYPE)"

# -----------------------------
# Build Query based on Entity Type
# -----------------------------
declare -a IDS
declare -a TEXTS
declare -a VOICES

if [ "$ENTITY_TYPE" == "audio_dialogue_lines" ]; then
    # Join to get specific character voice. 
    # If no identity found, defaults to 'alloy' (a standard Pollinations voice)
    SQL_QUERY="
    SELECT 
        t1.id, 
        t1.description, 
        COALESCE(t2.name, 'alloy') 
    FROM audio_dialogue_lines t1 
    LEFT JOIN audio_voice_identity t2 ON t1.audio_voice_identity_id = t2.id 
    WHERE t1.regenerate_audios=1"
else
    # For SFX/Ambience fallback
    SQL_QUERY="
    SELECT 
        id, 
        description, 
        'alloy' 
    FROM $ENTITY_TYPE 
    WHERE regenerate_audios=1"
fi

# -----------------------------
# Fetch Data
# -----------------------------
while IFS=$'\t' read -r id text voice; do
  IDS+=("$id")
  TEXTS+=("$text")
  VOICES+=("$voice")
done < <(mysql $MYSQL_ARGS -N -e "$SQL_QUERY" 2>/dev/null)

TOTAL=${#IDS[@]}

if [ "$TOTAL" -eq 0 ]; then
    echo "[Wrapper] No entities found flagged for audio generation."
    exit 0
fi

echo "[Wrapper] Found $TOTAL entities flagged for Pollinations TTS generation."

# -----------------------------
# Process Loop
# -----------------------------
for i in "${!IDS[@]}"; do
  E_ID="${IDS[$i]}"
  E_TEXT="${TEXTS[$i]}"
  E_VOICE="${VOICES[$i]}"

  # SAFETY NET: Force Sentence Breaks
  # 1. Replace newlines with " . " (period + space).
  # 2. Replace multiple spaces with single space.
  E_TEXT_CLEAN=$(echo "$E_TEXT" | sed ':a;N;$!ba;s/[\r\n]\+/ . /g' | tr -s ' ')

  echo "[Processing $((i+1))/$TOTAL] ID:$E_ID Voice:$E_VOICE"

  # Invoke the synchronous Pollinations worker script
  "$SCRIPT_DIR/gendia_db.sh" "$E_TEXT_CLEAN" "$MAP_RUN_ID" "$ENTITY_TYPE" "$E_ID" "$E_VOICE"

  # Update active_map_run_id on the entity
  mysql $MYSQL_ARGS -e "
    UPDATE $ENTITY_TYPE 
    SET active_map_run_id = '$MAP_RUN_ID'
    WHERE id = '$E_ID';
  " 2>/dev/null

  # Short sleep between API calls
  sleep 2

done

echo "[Wrapper] Finished processing audios for '$ENTITY_TYPE'."
