#!/bin/bash

# Usage: ./genframes_fromdb.sh prompt_type [limit_for_styles] [offset_for_styles] [no_styles] [add_to_prompt]

# Always resolve the directory of the current script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"


# Get MySQL CLI arguments from db_name.sh mian-conn
MYSQL_ARGS=$("$SCRIPT_DIR"/db_name.sh main-conn)
							# Example query: get the last frame number
#LAST_FRAME=$(mysql $MYSQL_ARGS -N -e "SELECT MAX(frame_number) FROM frames;")



PROMPT_TYPE="$1"       # e.g., character, anima, background, location
LIMIT="$2"             # optional, max number of styles to apply per entity
OFFSET="$3"            # optional, start from this style line (1-based)
NO_STYLES="$4"         # optional, 1 = skip styles, 0 = apply styles (default 0)
ADD_TO_PROMPT="$5"     # optional, text to append to each prompt

NO_STYLES=${NO_STYLES:-0}  # default to 0 if not provided

DB_USER="root"
DB_NAME=$("$(dirname "$0")/db_name.sh")

if [ -z "$PROMPT_TYPE" ]; then
  echo "Usage: $0 prompt_type [limit_for_styles] [offset_for_styles] [no_styles] [add_to_prompt]"
  exit 1
fi


# -----------------------------
# Create a new map_run for this script invocation
# -----------------------------
MAP_RUN_ID=$(mysql $MYSQL_ARGS -N -e "
INSERT INTO map_runs (entity_type, note) 
VALUES ('$PROMPT_TYPE', 'Generated by genframes_fromdb.sh'); 
SELECT LAST_INSERT_ID();
")

echo "Created new map_run ID: $MAP_RUN_ID"


VIEW_NAME="v_prompts_${PROMPT_TYPE}"

# Fetch all entities flagged for regeneration
SQL_QUERY="SELECT id, prompt FROM $VIEW_NAME WHERE regenerate_images=1"

mysql -u $MYSQL_ARGS -N -e "$SQL_QUERY" | while IFS=$'\t' read -r ENTITY_ID ENTITY_PROMPT; do
  # Append add_to_prompt if provided
  if [ -n "$ADD_TO_PROMPT" ]; then
    FULL_PROMPT="$ENTITY_PROMPT $ADD_TO_PROMPT"
  else
    FULL_PROMPT="$ENTITY_PROMPT"
  fi




  # Get tunnel URL and export
  NGROK_URL=$("$SCRIPT_DIR/ngrok_tunnel.sh")
  export NGROK_URL



  echo "Processing ENTITY_ID=$ENTITY_ID ($PROMPT_TYPE) -> Prompt: $FULL_PROMPT"


  # Pass BASE_PROMPT and MAP_RUN_ID as the first two parameters and limit, offset, no_styles, and add_to_prompt to generation script
"$SCRIPT_DIR/genframe_db.sh" "$FULL_PROMPT" "$MAP_RUN_ID" "$PROMPT_TYPE" "$ENTITY_ID" "$LIMIT" "$OFFSET" "$NO_STYLES" "$ADD_TO_PROMPT"

# Update active_map_run_id for this entity
mysql -u $MYSQL_ARGS -e "
UPDATE ${PROMPT_TYPE} 
SET active_map_run_id = '$MAP_RUN_ID'
WHERE id = '$ENTITY_ID';
"

done

echo "Done processing prompts for type '$PROMPT_TYPE'."


