#!/bin/bash

# Usage: ./genframes_fromdb.sh prompt_type [limit] [offset] [no_styles] [add_to_prompt]

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MYSQL_ARGS=$("$SCRIPT_DIR"/db_name.sh main-conn)

PROMPT_TYPE="$1"
LIMIT="$2"
OFFSET="$3"
NO_STYLES="$4"
ADD_TO_PROMPT="$5"

NO_STYLES=${NO_STYLES:-0}

# -----------------------------
# Fetch Global Negative Prompt from DB
# -----------------------------
# We fetch 'description' from table 'prompt_negative_globals'
# Assuming you want ID=1. If you have multiple, change WHERE to 'active=1'
read -r GLOBAL_NEGATIVE_PROMPT < <(
  mysql $MYSQL_ARGS -N -e \
    "SELECT COALESCE(description,'') FROM prompt_negative_globals WHERE active=1 ORDER BY id DESC LIMIT 1;"
)

# Fallback in case DB is empty
GLOBAL_NEGATIVE_PROMPT=${GLOBAL_NEGATIVE_PROMPT:-"nsfw, bad quality, text"}

if [ -z "$PROMPT_TYPE" ]; then
  echo "Usage: $0 prompt_type [limit] [offset] [no_styles] [add_to_prompt]"
  exit 1
fi

# -----------------------------
# Create Map Run
# -----------------------------
MAP_RUN_ID=$(mysql $MYSQL_ARGS -N -e "
INSERT INTO map_runs (entity_type, note) 
VALUES ('$PROMPT_TYPE', 'Generated by genframes_fromdb.sh'); 
SELECT LAST_INSERT_ID();
")
echo "Created new map_run ID: $MAP_RUN_ID"

VIEW_NAME="v_prompts_${PROMPT_TYPE}"

# -----------------------------
# Fetch Data (ID, Prompt, Negative, Seed)
# -----------------------------
SQL_QUERY="
SELECT CONCAT_WS(CHAR(31),
  id,
  prompt,
  COALESCE(prompt_negative, ''),
  COALESCE(seed, '')
)
FROM $VIEW_NAME
WHERE regenerate_images = 1
"

declare -a ENTITY_IDS
declare -a ENTITY_PROMPTS
declare -a ENTITY_NEGATIVES
declare -a ENTITY_SEEDS

while IFS=$'\x1f' read -r id prompt neg seed; do
  ENTITY_IDS+=("$id")
  ENTITY_PROMPTS+=("$prompt")
  ENTITY_NEGATIVES+=("$neg")
  ENTITY_SEEDS+=("$seed")
done < <(mysql $MYSQL_ARGS -N -e "$SQL_QUERY")

TOTAL=${#ENTITY_IDS[@]}
echo "Found $TOTAL entities flagged for image generation."

for i in "${!ENTITY_IDS[@]}"; do
  ENTITY_ID="${ENTITY_IDS[$i]}"
  ENTITY_PROMPT="${ENTITY_PROMPTS[$i]}"
  ENTITY_SPECIFIC_NEGATIVE="${ENTITY_NEGATIVES[$i]}"
  ENTITY_SEED="${ENTITY_SEEDS[$i]}"
  
  CURRENT_INDEX=$((i + 1))

  # 1. Prompt
  if [ -n "$ADD_TO_PROMPT" ]; then
    FULL_PROMPT="$ENTITY_PROMPT $ADD_TO_PROMPT"
  else
    FULL_PROMPT="$ENTITY_PROMPT"
  fi

  # 2. Negative Prompt
  if [ -n "$ENTITY_SPECIFIC_NEGATIVE" ]; then
    COMBINED_NEGATIVE_PROMPT="$ENTITY_SPECIFIC_NEGATIVE, $GLOBAL_NEGATIVE_PROMPT"
  else
    COMBINED_NEGATIVE_PROMPT="$GLOBAL_NEGATIVE_PROMPT"
  fi

  echo "[Processing $CURRENT_INDEX/$TOTAL] ENTITY_ID=$ENTITY_ID"
  echo "   -> Prompt: ${FULL_PROMPT:0:50}..."
  echo "   -> Seed:   ${ENTITY_SEED:-Random}"

  # -----------------------------
  # Call Worker: Pass Negative ($2) and Seed ($3)
  # -----------------------------
  "$SCRIPT_DIR/genframe_db.sh" "$FULL_PROMPT" "$COMBINED_NEGATIVE_PROMPT" "$ENTITY_SEED" "$MAP_RUN_ID" "$PROMPT_TYPE" "$ENTITY_ID" "$LIMIT" "$OFFSET" "$NO_STYLES" "$ADD_TO_PROMPT"

  # Update active run
  mysql $MYSQL_ARGS -e "UPDATE ${PROMPT_TYPE} SET active_map_run_id = '$MAP_RUN_ID' WHERE id = '$ENTITY_ID';"
done

echo "Done processing prompts for type '$PROMPT_TYPE'."