#!/bin/bash

# Usage: ./genmaps_fromdb.sh entity_type

# -----------------------------
# Resolve script directory
# -----------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"


ENTITY_TYPE="$1"

if [ -z "$ENTITY_TYPE" ]; then
  echo "Usage: $0 entity_type"
  echo "Example: $0 controlnet_maps"
  exit 1
fi

DB_USER="root"
DB_NAME=$("$SCRIPT_DIR/db_name.sh")

# -----------------------------
# Create a new map_run for this script invocation
# -----------------------------
MAP_RUN_ID=$(mysql -u "$DB_USER" "$DB_NAME" -N -e "
INSERT INTO map_runs (entity_type, note) 
VALUES ('$ENTITY_TYPE', 'Generated by genmaps_fromdb.sh'); 
SELECT LAST_INSERT_ID();
")

echo "Created new map_run ID: $MAP_RUN_ID"

# -----------------------------
# View & query
# -----------------------------
VIEW_NAME="v_prompts_${ENTITY_TYPE}"
SQL_QUERY="SELECT id, prompt FROM $VIEW_NAME WHERE regenerate_images=1"

# -----------------------------
# Iterate entities
# -----------------------------
mysql -u "$DB_USER" "$DB_NAME" -N -e "$SQL_QUERY" | while IFS=$'\t' read -r ENTITY_ID ENTITY_PROMPT; do
  echo "Processing ENTITY_ID=$ENTITY_ID ($ENTITY_TYPE) -> Prompt: $ENTITY_PROMPT"

  # Run genmap_db.sh
  "$SCRIPT_DIR/genmap_db.sh" "$MAP_RUN_ID" "$ENTITY_ID"

  # Update active_map_run_id
  mysql -u "$DB_USER" "$DB_NAME" -e "
    UPDATE ${ENTITY_TYPE}
    SET active_map_run_id = '$MAP_RUN_ID'
    WHERE id = '$ENTITY_ID';
  "
done

echo "✅ Done processing maps for type '$ENTITY_TYPE'."


