#!/bin/bash

# Usage: ./genmusics_fromdb.sh entity_type
# Example: ./genmusics_fromdb.sh audio_themes

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Ensure DB connection script exists
if [ ! -x "$SCRIPT_DIR/db_name.sh" ]; then
    echo "Error: db_name.sh not found."
    exit 1
fi

MYSQL_ARGS=$("$SCRIPT_DIR"/db_name.sh main-conn)
ENTITY_TYPE="$1"

if [ -z "$ENTITY_TYPE" ]; then
  echo "Usage: $0 entity_type"
  exit 1
fi

# -----------------------------
# Create a new map_run
# -----------------------------
# 2>/dev/null silences MySQL warnings (like "Using a password on CLI is insecure")
MAP_RUN_ID=$(mysql $MYSQL_ARGS -N -e "
INSERT INTO map_runs (entity_type, note) 
VALUES ('$ENTITY_TYPE', 'Generated by genmusics_fromdb.sh (Pollinations AI)'); 
SELECT LAST_INSERT_ID();
" 2>/dev/null)

echo "[Wrapper] Started. Map Run ID: $MAP_RUN_ID ($ENTITY_TYPE)"

# -----------------------------
# Build Query based on Entity Type
# -----------------------------
declare -a IDS
declare -a TEXTS
declare -a MODELS

# We use REPLACE to ensure clean text for the shell array
if [ "$ENTITY_TYPE" == "audio_dialogue_lines" ]; then
    SQL_QUERY="
    SELECT 
        t1.id, 
        REPLACE(REPLACE(t1.description, '\r', ' '), '\n', ' '), 
        COALESCE(t2.name, 'suno') 
    FROM audio_dialogue_lines t1 
    LEFT JOIN audio_voice_identity t2 ON t1.audio_voice_identity_id = t2.id 
    WHERE t1.regenerate_audios=1"
else
    SQL_QUERY="
    SELECT 
        id, 
        REPLACE(REPLACE(description, '\r', ' '), '\n', ' '), 
        'suno' 
    FROM $ENTITY_TYPE 
    WHERE regenerate_audios=1"
fi

# -----------------------------
# Fetch Data
# -----------------------------
# 2>/dev/null silences errors if query is empty or connection blips
while IFS=$'\t' read -r id text model; do
  IDS+=("$id")
  TEXTS+=("$text")
  MODELS+=("$model")
done < <(mysql $MYSQL_ARGS -N -e "$SQL_QUERY" 2>/dev/null)

TOTAL=${#IDS[@]}

if [ "$TOTAL" -eq 0 ]; then
    echo "[Wrapper] No entities found flagged for music generation."
    exit 0
fi

echo "[Wrapper] Found $TOTAL entities."

# -----------------------------
# Process Loop
# -----------------------------
for i in "${!IDS[@]}"; do
  E_ID="${IDS[$i]}"
  E_TEXT="${TEXTS[$i]}"
  E_MODEL="${MODELS[$i]}"

  # Clean text: remove multiple spaces
  E_TEXT_CLEAN=$(echo "$E_TEXT" | tr -s ' ')

  echo "[Processing $((i+1))/$TOTAL] ID:$E_ID Model:$E_MODEL"

  # Invoke the worker script
  "$SCRIPT_DIR/genmusic_db.sh" "$E_TEXT_CLEAN" "$MAP_RUN_ID" "$ENTITY_TYPE" "$E_ID" "$E_MODEL"

  # Update active_map_run_id on the entity
  mysql $MYSQL_ARGS -e "
    UPDATE $ENTITY_TYPE 
    SET active_map_run_id = '$MAP_RUN_ID'
    WHERE id = '$E_ID';
  " 2>/dev/null

  # Short sleep
  sleep 2
done

echo "[Wrapper] Finished."
