#!/bin/bash
# hotspot_echo.sh - Automatically update pyapi_echo.sh with tablet's IP when on hotspot

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PYAPI_ECHO_FILE="$SCRIPT_DIR/pyapi_echo.sh"

# Run hotspot script to get network info
echo "Detecting hotspot network and devices..."
echo ""

# Get phone's hotspot IP
PHONE_IP=$(ifconfig 2>/dev/null | awk '/ap0:/ {flag=1; next} /flags=/ && flag==1 {flag=0} flag==1 && /inet / {print $2; exit}')

if [ -z "$PHONE_IP" ]; then
    echo "Hotspot not active or cannot detect IP"
    exit 1
fi

NETWORK=$(echo $PHONE_IP | cut -d'.' -f1-3)
echo "Phone IP: $PHONE_IP"
echo "Network range: $NETWORK.0/24"
echo ""

# Try common tablet IPs first (especially .8 based on your experience)
TABLET_IP=""
PORT="8009"

echo "Checking for tablet at common IPs..."
for i in 8; do
    ip="$NETWORK.$i"
    
    # Skip the phone's own IP
    if [ "$ip" = "$PHONE_IP" ]; then
        continue
    fi
    
    echo -n "Checking $ip... "
    if ping -c 1 -W 1 "$ip" >/dev/null 2>&1; then
        echo "✓ Found!"
        
        # Additional check: try to see if port 8009 is accessible (optional)
        if timeout 2 bash -c "cat < /dev/null > /dev/tcp/$ip/$PORT" 2>/dev/null; then
            echo "  ✓ Port $PORT is also accessible!"
            TABLET_IP="$ip"
            break
        else
            echo "  ? Device found but port $PORT not accessible (might still be tablet)"
            TABLET_IP="$ip"
            # Continue checking other IPs in case this isn't the tablet
        fi
    else
        echo "✗ Not found"
    fi
done

# If not found in common IPs, do a quick scan
if [ -z "$TABLET_IP" ]; then
    echo ""
    echo "Doing quick scan of network range..."
    
    # Scan limited range for efficiency
    for i in {1..30}; do
        ip="$NETWORK.$i"
        
        if [ "$ip" = "$PHONE_IP" ]; then
            continue
        fi
        
        if ping -c 1 -W 1 "$ip" >/dev/null 2>&1; then
            echo "✓ Found device at $ip"
            TABLET_IP="$ip"
            break
        fi
    done
fi

if [ -z "$TABLET_IP" ]; then
    echo ""
    echo "ERROR: Could not find tablet IP"
    echo "Make sure:"
    echo "1. Tablet is connected to phone's hotspot"
    echo "2. Tablet's local server is running on port $PORT"
    echo ""
    exit 1
fi

# Create the URL
URL="http://${TABLET_IP}:${PORT}"

echo ""
echo "Tablet found at: $TABLET_IP"
echo "Updating pyapi_echo.sh with: $URL"

# Overwrite pyapi_echo.sh
cat > "$PYAPI_ECHO_FILE" <<EOF
#!/bin/bash
# generated by hotspot_echo.sh
echo "$URL"
EOF

chmod +x "$PYAPI_ECHO_FILE"

echo ""
echo "Successfully updated: $PYAPI_ECHO_FILE"
echo "  $($PYAPI_ECHO_FILE)"
