#!/bin/bash

# Usage: ./mdttses_fromdb.sh
# Iterates documentations marked for audio regeneration
# Uses PHP CLI with Output Buffering to prevent PHP Warnings from leaking into Audio

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MYSQL_ARGS=$("$SCRIPT_DIR"/db_name.sh main-conn)

# 1. Resolve Project Root
if [ -f "$SCRIPT_DIR/load_root.sh" ]; then
  source "$SCRIPT_DIR/load_root.sh"
fi
if [ -z "$PROJECT_ROOT" ]; then
   PROJECT_ROOT="$(cd "$(dirname "$SCRIPT_DIR")" && pwd)"
fi

# 2. Create a temporary PHP helper
# We use output buffering (ob_start/ob_end_clean) to silence any
# deprecation warnings from Parsedown or the Bootstrap process.
PHP_HELPER="$SCRIPT_DIR/_tmp_get_md.php"

cat << 'EOF' > "$PHP_HELPER"
<?php
// Start buffering immediately to catch any premature output/warnings
ob_start();

require_once __DIR__ . '/../public/bootstrap.php';
require __DIR__ . '/../public/env_locals.php';

// Force suppress errors (again, in case bootstrap overrode it)
error_reporting(0);
ini_set('display_errors', '0');

$docId = $argv[1] ?? 0;

if (!$docId) {
    ob_end_clean();
    exit;
}

$stmt = $pdo->prepare("SELECT content FROM documentations WHERE id = ?");
$stmt->execute([$docId]);
$doc = $stmt->fetch(PDO::FETCH_ASSOC);

$finalText = "";

if ($doc && !empty($doc['content'])) {
    // 1. Parse Markdown
    $parsedown = new Parsedown();
    $html = $parsedown->text($doc['content']);

    // 2. Convert block elements to newlines
    $html = str_replace(
        ['</p>', '<br>', '<br />', '</h1>', '</h2>', '</h3>', '</h4>', '</h5>', '</h6>', '</li>', '</div>', '</blockquote>', '</pre>'], 
        "\n", 
        $html
    );

    // 3. Strip Tags and Decode
    $text = strip_tags($html);
    $text = html_entity_decode($text, ENT_QUOTES | ENT_HTML5);
    
    // 4. Cleanup whitespace
    $text = preg_replace('/\n\s*\n/', "\n\n", $text);
    
    $finalText = trim($text);
}

// Discard all buffer contents (warnings, notices, included whitespace)
ob_end_clean();

// Output ONLY the clean text
echo $finalText;
EOF

# 3. Create Map Run
MAP_RUN_ID=$(mysql $MYSQL_ARGS -N -e "
INSERT INTO map_runs (entity_type, note) 
VALUES ('documentations', 'Generated by mdttses_fromdb.sh'); 
SELECT LAST_INSERT_ID();
")
echo "Created new map_run ID: $MAP_RUN_ID"

# 4. Get IDs
declare -a IDS
while IFS=$'\t' read -r id; do
  IDS+=("$id")
done < <(mysql $MYSQL_ARGS -N -e "SELECT id FROM documentations WHERE regenerate_audios=1")

TOTAL=${#IDS[@]}
echo "Found $TOTAL documents flagged."

# 5. Process
for i in "${!IDS[@]}"; do
  DOC_ID="${IDS[$i]}"
  HUMAN_INDEX=$((i+1))
  
  echo "[Processing $HUMAN_INDEX/$TOTAL] Doc ID: $DOC_ID"

  # FETCH CLEAN TEXT
  CLEAN_TEXT=$(php "$PHP_HELPER" "$DOC_ID")

  if [ -z "$CLEAN_TEXT" ]; then
    echo "  -> Error: Text content empty or extraction failed."
    continue
  fi

  # Call the dedicated worker
  "$SCRIPT_DIR/mdtts_db.sh" "$CLEAN_TEXT" "$MAP_RUN_ID" "documentations" "$DOC_ID" "en_US-libritts_r-medium"

  # Update active_map_run_id
  mysql $MYSQL_ARGS -e "
    UPDATE documentations 
    SET active_map_run_id = '$MAP_RUN_ID'
    WHERE id = '$DOC_ID';
  "

  sleep 2
done

# Cleanup
rm -f "$PHP_HELPER"

echo "Done."
