#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# call the tunnel script once and capture URL
URL="$("$SCRIPT_DIR/zrok_tunnel.sh")" || {
  echo "ERROR: failed to obtain zrok URL" >&2
  exit 1
}

if [ -z "$URL" ]; then
  echo "ERROR: empty URL returned by zrok_tunnel.sh" >&2
  exit 2
fi

# overwrite zrok_echo.sh with a tiny script that echoes the URL
cat > "$SCRIPT_DIR/zrok_echo.sh" <<EOF
#!/bin/bash
# generated by zrok_update.sh
echo "$URL"
EOF

chmod +x "$SCRIPT_DIR/zrok_echo.sh"

# optional: print success so you know it wrote the file
echo "Updated: $SCRIPT_DIR/zrok_echo.sh -> $URL"
